dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: docker
      pass: docker
      dbname: postgres
      schema: dbt_your_name

    docker:
      type: postgres
      threads: 4
      host: postgres_instance
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: postgres
      schema: docker

    prod:
      type: postgres
      threads: 4
      host: [host]
      port: [port]
      user: [user]
      pass: [password]
      dbname: [dbname]
      schema: [schema]
