dbt_project:
  target: "{{ env_var('DBT_ENV', 'local') }}"
  outputs:
    local:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: postgres
      schema: dbt_your_name

    docker:
      type: postgres
      threads: 4
      host: postgres_instance
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: postgres
      schema: dbt_docker

    prod:
      type: postgres
      threads: 4
      host: "{{ env_var('DBT_HOST') }}"
      port: 5432
      user: "{{ env_var('DBT_USER') }}"
      pass: "{{ env_var('DBT_PASSWORD') }}"
      dbname: "{{ env_var('DBT_DBNAME') }}"
      schema: "{{ env_var('DBT_PRD_SCHEMA') }}"
