dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: docker
      pass: docker
      dbname: postgres
      schema: dbt_your_name

    local_image:
      type: postgres
      threads: 4
      host: dbt-with-docker-postgres-1
      port: 5432
      user: docker
      pass: docker
      dbname: postgres
      schema: local_image

    prod:
      type: postgres
      threads: 4
      host: [host]
      port: [port]
      user: [user]
      pass: [password]
      dbname: [dbname]
      schema: [schema]
