repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-added-large-files
      - id: check-yaml

-   repo: https://github.com/Yelp/detect-secrets
    rev: v1.2.0
    hooks:
    -   id: detect-secrets

-   repo: https://github.com/sqlfluff/sqlfluff
    rev: 1.1.0
    hooks:
      - id: sqlfluff-lint
        args: ['--dialect', 'postgres']
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
      - id: sqlfluff-fix
        args: [ '--force','--dialect', 'postgres']
        additional_dependencies: ['dbt-postgres', 'sqlfluff-templater-dbt']
