services:
  postgres:
    image: ${POSTGRES_IMAGE}
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
