services:
  postgres:
    image: "${POSTGRES_IMAGE}"
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: "${DBT_USER}"
      POSTGRES_PASSWORD: "${DBT_PASSWORD}"
    ports:
      - 5432:5432
