version: "3.9"

services:
  postgres:
    image: postgres:14.3
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432

networks:
  default:
    name: dbt_network
