services:
  postgres:
    image: postgres:14.3
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
    
  dbt:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: dbt_instance
    env_file:
      - .env
      - .secrets.env


networks:
  default:
    name: dbt_network
