services:
  postgres:
    image: postgres:14.3
    container_name: postgres_instance
    restart: always
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: docker
      POSTGRES_PASSWORD: docker
    ports: 
      - 5432:5432
  dbt:
    image: ${IMAGE_NAME}:${IMAGE_VERSION}
    container_name: dbt_instance
    command: '/bin/sh -c "trap : TERM INT; (while true; do sleep 1000; done) & wait"'
    deploy:
      replicas: ${DBT_INSTANCE:-0}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./dbt_project:/root/dbt_project
    environment:
      - DBT_ENV=docker
    env_file:
      - .env
      - .secrets.env


networks:
  default:
    name: dbt_network
