name: 'project'
version: '0.1.0'
config-version: 2

profile: 'project'

model-paths: ["project/models"]
analysis-paths: ["project/analyses"]
test-paths: ["project/tests"]
seed-paths: ["project/seeds"]
macro-paths: ["project/macros"]
snapshot-paths: ["project/snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  project:
    example:
      +materialized: table
