name: 'dbt_project'
version: '0.1.0'
config-version: 2

profile: 'dbt_project'

model-paths: ["dbt_project/models"]
analysis-paths: ["dbt_project/analyses"]
test-paths: ["dbt_project/tests"]
seed-paths: ["dbt_project/seeds"]
macro-paths: ["dbt_project/macros"]
snapshot-paths: ["dbt_project/snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  dbt_project:
    example:
      +materialized: view
