dbt_project:
  target: dev
  outputs:
    dev:
      type: postgres
      threads: 4
      host: localhost
      port: 5432
      user: docker
      pass: docker
      dbname: postgres
      schema: dbt_your_name

    prod:
      type: postgres
      threads: 4
      host: [host]
      port: [port]
      user: docker
      pass: docker
      dbname: [dbname]
      schema: public

  